### ISSUE TITLE
ファイルのインデントをそろえる

### ISSUE THREAD

**Issue by gotoeveryone** [ohnishi26/HP#2]
- html, css, js いずれにおいても発生している
- タグ開閉の対応やクラスに適用したスタイルの範囲が見えづらく、修正不備につながる

### インデントがそろっていない例

```html
 <div>
 <a href="test.html">test</a>
  <span>test
</span>
</div>
```

```css
.test {
display: block;
  color: red;
 height: 20px;
 }
```

### インデントがそろっている例

```html
<div>
  <a href="test.html">test</a>
  <span>test</span>
</div>
```

```css
.test {
  display: block;
  color: red;
  height: 20px;
}
```
