### ISSUE TITLE
float ではなく flex や grid を使う

### ISSUE THREAD

**Issue by gotoeveryone** [ohnishi26/HP#4]
- float を使うと要素の位置関係やサイズ、解除のタイミングを常に意識する必要がある
- 横並びレイアウトなら `display: flex` や `dispaly: grid` が使える
  - 要素幅を超えた場合の改行や、要素を並べる間隔・方向も制御できる

### flexbox を使った例

```html
<div class="flex-center">
  <div class="flex-basis-60">横並び1</div>
  <div class="flex-basis-40">横並び2</div>
</div>
```

```css
.flex-center {
  display: flex;
  align-items: center; /* 縦位置中央寄せ */
  justify-content: center; /* 横位置中央寄せ */
}

.flex-basis-60 {
  flex-basis: 60%; /* flexbox 内のコンテンツは flex-basis で幅を決める */
}

.flex-basis-40 {
  flex-basis: 40%;
}
```
